### ISSUE TITLE
Please provide a license

### ISSUE THREAD

**Issue by nooproblem** [mullvad/udp-over-tcp#43]
Firstly, thanks for making this great piece of software!

Secondly, could you please provide a license, because apart from this one line below in the Cargo.toml file, it is ambiguous if anyone else is able to rebuild, redistribute, copy, modify etc.

https://github.com/mullvad/udp-over-tcp/blob/87936ac29b68b902565955f138ab02294bcc8593/Cargo.toml#L5

Thanks in advance!

**Comment by faern** [comment]
Fixed in #59
